version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    versioning-strategy: increase
    target-branch: "main"
    labels:
      - "pip dependencies"
